FROM pitkley/rust:stable

ENV PATH "/root/.cargo/bin:$PATH"

RUN \
    # Install required packages
    apt-get update \
    && apt-get install -y --no-install-recommends \
        libssl-dev \
        make \
        pkg-config \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
