name: ssh-test

on:
  push:
    branches:
    - ssh-test

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup connection to arm64-capable runner
      run: |
        echo "::group::ssh-agent: launch and export"
        eval "$(ssh-agent)"
        echo "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" >> $GITHUB_ENV
        echo "SSH_AGENT_PID=$SSH_AGENT_PID" >> $GITHUB_ENV
        echo "::endgroup::"
        
        echo "::group::ssh-agent: load private key"
        ssh-add - <<< "${{ secrets.ARMRUNNER1_SSH_PRIVATE_KEY }}"
        echo "::endgroup::"
        
        echo "::group::ssh: pin runner public key"
        mkdir ~/.ssh && chmod 0700 ~/.ssh || :
        echo "[${{ secrets.ARMRUNNER1_HOSTNAME }}]:${{ secrets.ARMRUNNER1_SSH_PORT }} ${{ secrets.ARMRUNNER1_SSH_HOSTKEY }}" > ~/.ssh/known_hosts
        echo "::endgroup::"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Show current supported platforms
      run: docker buildx inspect
    - name: Append to Buildx builder
      env:
        DOCKER_HOST: ssh://github-actions@${{ secrets.ARMRUNNER1_HOSTNAME }}:${{ secrets.ARMRUNNER1_SSH_PORT }}
      run: docker buildx create --append --name ${{ steps.buildx.outputs.name }} --bootstrap
    - name: Show current supported platforms
      run: docker buildx inspect

    - name: Checkout
      uses: actions/checkout@v2
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: multiplatformtest/.
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: false
        tags: pitkley/dfw-multiplatformtest:latest
